[package]
name = "jwt_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.46", features = ["derive"] }
eyre = "0.6.12"
jsonwebtoken = "9.3.1"
serde = { version = "1.0.219", features = ["derive"] }
